### ISSUE TITLE
LoginEmailFragment: "Already managing a GoogleApiClient"

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Login-Flow-Android#7]
The WCAndroid and WPAndroid apps both have "Already managing a GoogleApiClient" crashes in `LoginEmailFragment`:

http://crashes.to/s/aab765a1feb
http://crashes.to/s/6efb6866862

Possible fixes:

https://stackoverflow.com/a/37025744/1673548
https://stackoverflow.com/a/42934594/1673548

**Comment by malinajirka** [comment]
I believe [this change](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/pull/27) might have fixed this issue. I'd suggest closing it for now and re-open it if necessary. Wdyt @nbradbury ?

**Comment by nbradbury** [comment]
@malinajirka I think you're right - adding the "stopAutoManage" and "disconnect" steps very likely fixed this. I'll close this.
